image:
  file: .gitpod.Dockerfile
tasks:
  - init: make build && blocklet server init -f --mode debug
    command: blocklet server start && blocklet dev
ports:
  - port: 8080
    onOpen: ignore
    visibility: public
  - port: 8089
    onOpen: ignore
  - port: 8090
    onOpen: ignore
